modal window opening and closing implemented.
galitsina/react-stellar-burger pull request #2
Opened 2023-05-26 15:32 UTC by galitsina

2023-05-27 13:54 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу на втором этапе вашего спринта, добавили корректно модальные окна и построили с ними взаимодействие, улучшили код, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Не нужно передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг во внешнем компоненте;
- Следует проверить использование `propTypes` на предмет `isRequired` и передачи типа ингредиента во всех обновленных файлах. Следует передавать объект ингредиента целиком, не разбивая его на отдельные пропсы;
- Имена констант принято записывать в стиле UPPER_CASE;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-05-27 13:54 UTC, randomroot commented on src/components/App/App.jsx
> +      fetch(url)
🟡 **Можно улучшить:**

В дальнейшем добавятся ещё запросы к бэкенду и лучше разместить их в отдельном файле  `utils/burger-api.js`

Например:

```js

const NORMA_API = `https://norma.nomoreparties.space/api`;

export function getIngredients() {
   return fetch(`${NORMA_API}/ingredients`)
    .then(checkReponse )
}

export function sendOrder(data) {
   return fetch(`${NORMA_API}/orders`)
    .then(checkReponse )
}

```

, а не описывать запросы в самом компоненте

Проверка ответа сервера и преобразование из json скоро будет дублироваться в нескольких местах, поэтому целесообразно вынести её в отдельную функцию:

```js
const checkResponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-05-27 13:54 UTC, randomroot commented on src/components/App/App.jsx
> +      {state.length &&
🟡 **Можно улучшить:**

По умолчанию отображается "0" на экране, пока нет данных, лучше добавить лоадер или обернуть выражение в `Boolean(state.length)`

2023-05-27 13:54 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    <Modal closeModal={handleCloseModal} component={orderDetails} modalOpened={open}/>
🔴 **Нужно исправить:**

Не следует передавать условие открытия в попап и размещать логику открытия там. Рендерите компонент попапа только, если он открыт, используя для этого условный рендеринг

```js
{isOpen && (
    компонент открываемого попапа
)}
``

2023-05-27 13:54 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +  const [open, setOpen] = React.useState();
🟡 **Можно улучшить:**

Целесообразно указать начальное состояние стейта

2023-05-27 13:54 UTC, randomroot commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  ingredientPropType,
🔴 **Нужно исправить:**

В данном случае на вход ожидаются два пропса: `ingredientPropType` и `openModal`. Для того, чтобы совместить типы необходимо воспользоваться оператором spread оператором: `...ingredientPropType`.
Но целесообразно создать пропс `ingredient: ingredientPropType` и передавать в него значение ингредиента. Объект в компонент обычно передается целиком, за исключение случаев, когда нужно пара свойств

2023-05-27 13:54 UTC, randomroot commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  const {image, price, title, openModal, _id} = props;
🟡 **Можно улучшить:**

Деструктуризацию можно перенести выше, вместо `(props)` => `({ ... })`

2023-05-27 13:54 UTC, randomroot commented on src/components/IngredientDetails/IngredientDetails.jsx
> +IngredientDetails.propTypes = {ingredientPropType};
🔴 **Нужно исправить:**

Аналогично с компонентом `BurgerIngredients`: так вы не создаете копию объекта, а создаете объект с единственным ключом `ingredientPropType` с типом `ingredientPropType`.

Укажите в `propTypes` -> `{ ingredient: ingredientPropType }` и передавайте объект целиком, декомпозируя его тут

2023-05-27 13:54 UTC, randomroot commented on src/components/IngredientGroup/IngredientGroup.jsx
> +    setIngredient({})
🟡 **Можно улучшить:**

Не рекомендуется использовать пустой объект в качестве пустого значения, для такого случаю существуют `null` или `undefined`, что позволит избежать ошибок при автоматическом приведении типов и проверках

2023-05-27 13:54 UTC, randomroot commented on src/components/IngredientGroup/IngredientGroup.jsx
> +IngredientGroup.propTypes = { ingredientPropType };
🔴 **Нужно исправить:**

Аналогично по типизации выше

2023-05-27 13:54 UTC, randomroot commented on src/components/Modal/Modal.jsx
> +  ingredientPropType,
🔴 **Нужно исправить:**

1) Аналогично по типизации выше;
2) В описании `propTypes` этого и других компонентов нужно указывать `.isRequired` у пропсов, без этого не контролируется, что пропс передается. Проверьте во всем проекте

2023-05-27 13:54 UTC, randomroot commented on src/components/App/App.jsx
> +        .catch((err) => {console.log(`Произошла ошибка: ${err}`)})
🟡 **Можно улучшить:**

Хорошо, что обрабатывается ошибка запроса к `api`, но можно сделать еще лучше - сохранять в state и показывать пользователю ошибку в интерфейсе, чтобы он понимал что происходит

2023-05-27 13:54 UTC, randomroot commented on src/components/App/App.jsx
> +const url = 'https://norma.nomoreparties.space/api/ingredients';
🟡 **Можно улучшить:**

Хорошо, что вы вынесли урл в отдельную константу, но лучше вынесьте базовый адрес сервера `https://norma.nomoreparties.space/api` сервера , а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`


🔴 **Нужно исправить:**

Имена констант принято записывать в стиле UPPER_CASE

2023-05-29 10:52 UTC, galitsina commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    <Modal closeModal={handleCloseModal} component={orderDetails} modalOpened={open}/>
Изначально я так и делала: открывала попап, используя условный рендеринг. Это приводит к резкому открытию попапа. Задачи плавно открывать окно не было, но хотелось добавить красоты. Именно таким образом (добавлением класса) я решала задачу плавного открытия попапа с помощью css. Я исправила на открытие с помощью условного рендеринга. Подскажите, можно ли посредством реакта плавно открывать окно?

2023-05-30 07:06 UTC, randomroot commented on src/components/IngredientGroup/IngredientGroup.jsx
> +    <Modal closeModal={handleCloseModal} component={ingredientDetails}>Детали ингредиента</Modal>
🟡 **Можно улучшить:**

Имеет смысл не выносить в константу компонент, чтобы не инициализировать его, когда он не нужен, несмотря на то, что на экране он не отображается

2023-05-30 07:06 UTC, randomroot commented on src/components/IngredientGroup/IngredientGroup.jsx
> +  ingredients: PropTypes.arrayOf(ingredientPropType).isRequired,
🟡 **Можно улучшить:**

Элементы массива следует также указывать как `isRequired`, если не ожидается пустых значений внутри массива:
```js
(ingredientPropType.isRequired).isRequired
```

2023-05-30 07:06 UTC, randomroot commented on src/components/BurgerIngredient/BurgerIngredient.jsx
> +  ingredient: ingredientPropType,
🟡 **Можно улучшить:**

Данный пропс следует указать как `isRequired`

2023-05-30 07:06 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    <Modal closeModal={handleCloseModal} component={orderDetails} modalOpened={open}/>
Добрый день!

Реализацию плавного открытия можно реализовать также через CSS:

2023-05-30 07:07 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, так держать👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-05-30 09:07 UTC, merged